services:
  - redis-server
before_install:
  - git submodule update --init --recursive
  - sudo apt-get install -y libevent-dev python-dev
language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: make test
